flowchart LR

%% In this diagram we leave layer UI behind the scenes.
%% We only study its structure and internal dependencies.
%% 
%% - Subgraphs are systems
%% - Nodes are components
%% - Subgraphs are components as well

HasqlGen --> GenSdk

%% The general adapter lib
subgraph GenSdk
  Project[Project Model]
  AdapterInterface[Adapter Interface]
  AdapterInterface --> Project
end

subgraph HasqlGen
  Adapter --> Generate
  Adapter --> Config
  Generate --> Config
  
  subgraph Generate
    subgraph Algebras
      Module
      File
      Module --> File
    end
    subgraph Modules
      Statement
      Statements
      Statements --> Statement
    end
    subgraph Files
      Cabal
    end
    Modules --> Algebras
    Files --> Algebras
    Package --> Modules
    Package --> Files
  end
end

